import { Relationship } from '@/lib/store'

export type RelationSide = 'p1' | 'p2'

export interface RelationQuestion {
  id: string
  text: string
  bucket: string
}

// questions[relationship][side] = 30 prompts each (uplifting/positive/funny)
export const questions: Record<Relationship, Record<RelationSide, RelationQuestion[]>> = {
  'kid-parent': {
    // P1 is Kid
    p1: [
      { id: 'kp-k-1', text: "What's the funniest thing I did as a toddler that you still laugh about?", bucket: 'memories' },
      { id: 'kp-k-2', text: "If our family had a theme song, what would it be—and why?", bucket: 'fun' },
      { id: 'kp-k-3', text: "Tell me a story about when you were my age—what was your favorite snack?", bucket: 'childhood' },
      { id: 'kp-k-4', text: "What tiny thing do I do that secretly makes you proud?", bucket: 'pride' },
      { id: 'kp-k-5', text: "What family rule makes the least sense—and should we replace it with a sillier one?", bucket: 'house' },
      { id: 'kp-k-6', text: "Describe our perfect lazy Sunday—minute by minute.", bucket: 'routine' },
      { id: 'kp-k-7', text: "What did you think I would be obsessed with—but I surprised you?", bucket: 'surprise' },
      { id: 'kp-k-8', text: "What's a joke I told that you actually loved?", bucket: 'humor' },
      { id: 'kp-k-9', text: "What chore am I secretly great at (even if I complain)?", bucket: 'home' },
      { id: 'kp-k-10', text: "If I could borrow one of your superpowers, which should it be?", bucket: 'superpowers' },
      { id: 'kp-k-11', text: "When did you realize our family is wonderfully weird?", bucket: 'identity' },
      { id: 'kp-k-12', text: "Tell me about a time I made your day better without knowing it.", bucket: 'kindness' },
      { id: 'kp-k-13', text: "What school subject did you not like—but wish you did?", bucket: 'school' },
      { id: 'kp-k-14', text: "What is a food you loved as a kid that I might like to try?", bucket: 'food' },
      { id: 'kp-k-15', text: "What's a family tradition you'd love us to start this year?", bucket: 'tradition' },
      { id: 'kp-k-16', text: "If our pet could talk for one minute, what would it say about me?", bucket: 'pets' },
      { id: 'kp-k-17', text: "What's something you wish you had learned earlier that I can learn now?", bucket: 'advice' },
      { id: 'kp-k-18', text: "Which emoji describes me at breakfast? Explain with evidence.", bucket: 'fun' },
      { id: 'kp-k-19', text: "When do I remind you most of yourself?", bucket: 'likeness' },
      { id: 'kp-k-20', text: "What's a tiny habit that makes our home happier?", bucket: 'home' },
      { id: 'kp-k-21', text: "Tell me a story about a silly mistake that turned into a great memory.", bucket: 'memories' },
      { id: 'kp-k-22', text: "What is your secret recipe for cheering me up?", bucket: 'care' },
      { id: 'kp-k-23', text: "If we swapped roles for a day, what would you do first?", bucket: 'imagination' },
      { id: 'kp-k-24', text: "What's something I do now that future-me will be proud of?", bucket: 'future' },
      { id: 'kp-k-25', text: "What song should we dance to right after this recording?", bucket: 'fun' },
      { id: 'kp-k-26', text: "What chore would you gladly trade with me—and why?", bucket: 'home' },
      { id: 'kp-k-27', text: "What's a family nickname I should absolutely never lose?", bucket: 'identity' },
      { id: 'kp-k-28', text: "If our fridge could talk, what gossip would it share about us?", bucket: 'fun' },
      { id: 'kp-k-29', text: "What is your favorite way that I show kindness?", bucket: 'kindness' },
      { id: 'kp-k-30', text: "Describe your favorite place at home and what makes it cozy.", bucket: 'home' }
    ],
    // P2 is Parent
    p2: [
      { id: 'kp-p-1', text: "What made you proud of me this week (even a tiny thing)?", bucket: 'pride' },
      { id: 'kp-p-2', text: "Tell me about something brave you did when you were my age.", bucket: 'bravery' },
      { id: 'kp-p-3', text: "If we start a new bedtime ritual, what should it be?", bucket: 'ritual' },
      { id: 'kp-p-4', text: "What household job did you secretly enjoy as a kid?", bucket: 'home' },
      { id: 'kp-p-5', text: "What is one rule you wish you had broken—just a little?", bucket: 'fun' },
      { id: 'kp-p-6', text: "Teach me your quickest way to turn a bad day around.", bucket: 'advice' },
      { id: 'kp-p-7', text: "What made your favorite teacher so memorable?", bucket: 'school' },
      { id: 'kp-p-8', text: "What is the silliest outfit you ever wore on purpose?", bucket: 'humor' },
      { id: 'kp-p-9', text: "Tell me a story about a time you laughed so hard you cried.", bucket: 'memories' },
      { id: 'kp-p-10', text: "What is something I do that makes our home kinder?", bucket: 'kindness' },
      { id: 'kp-p-11', text: "What adventure should we plan together this month?", bucket: 'adventure' },
      { id: 'kp-p-12', text: "What snack should always be in the pantry for emergency joy?", bucket: 'food' },
      { id: 'kp-p-13', text: "When did you realize you were growing up—and how did it feel?", bucket: 'growing' },
      { id: 'kp-p-14', text: "Which of my jokes deserves a trophy?", bucket: 'humor' },
      { id: 'kp-p-15', text: "What tiny habit helps you stay calm on busy days?", bucket: 'habits' },
      { id: 'kp-p-16', text: "What do you hope I remember about our family when I'm older?", bucket: 'future' },
      { id: 'kp-p-17', text: "If our pet kept a diary, what would it write about me today?", bucket: 'pets' },
      { id: 'kp-p-18', text: "Tell me a story about a small kindness that meant a lot to you.", bucket: 'kindness' },
      { id: 'kp-p-19', text: "What's a movie you loved as a kid that we should watch together?", bucket: 'media' },
      { id: 'kp-p-20', text: "If we could time-travel for one afternoon, where would we go?", bucket: 'imagination' },
      { id: 'kp-p-21', text: "What word best describes our family energy—and why?", bucket: 'identity' },
      { id: 'kp-p-22', text: "What's a small tradition from your childhood we could revive?", bucket: 'tradition' },
      { id: 'kp-p-23', text: "When did you feel most supported by your parents?", bucket: 'support' },
      { id: 'kp-p-24', text: "What's a talent you have that almost no one knows about?", bucket: 'talent' },
      { id: 'kp-p-25', text: "What would a perfect after-school hangout look like?", bucket: 'routine' },
      { id: 'kp-p-26', text: "If you could gift me one life tip, what would it be?", bucket: 'advice' },
      { id: 'kp-p-27', text: "What sound smells like home to you?", bucket: 'senses' },
      { id: 'kp-p-28', text: "What was your funniest kitchen experiment?", bucket: 'food' },
      { id: 'kp-p-29', text: "When do I make you feel seen?", bucket: 'connection' },
      { id: 'kp-p-30', text: "Describe your favorite cozy corner growing up.", bucket: 'home' }
    ]
  },

  'adultchild-parent': {
    // P1 is Adult Child
    p1: [
      { id: 'ap-ac-1', text: "What is something you were right about that I only admit now?", bucket: 'truths' },
      { id: 'ap-ac-2', text: "What cheap meal from my childhood still slaps?", bucket: 'food' },
      { id: 'ap-ac-3', text: "What did you worry about with me that turned out great?", bucket: 'reassurance' },
      { id: 'ap-ac-4', text: "Tell me a small parenting hack you wish you discovered sooner.", bucket: 'advice' },
      { id: 'ap-ac-5', text: "What's our funniest miscommunication of all time?", bucket: 'humor' },
      { id: 'ap-ac-6', text: "When did you realize I had become your equal in something?", bucket: 'growth' },
      { id: 'ap-ac-7', text: "What tradition should we keep even if we live far apart?", bucket: 'tradition' },
      { id: 'ap-ac-8', text: "What's a story you want me to pass down someday?", bucket: 'legacy' },
      { id: 'ap-ac-9', text: "What everyday thing about me makes you proud now?", bucket: 'pride' },
      { id: 'ap-ac-10', text: "What music from your era do you insist I appreciate?", bucket: 'music' },
      { id: 'ap-ac-11', text: "What do you miss from when I lived at home?", bucket: 'nostalgia' },
      { id: 'ap-ac-12', text: "Describe our best road-trip moment in 30 seconds.", bucket: 'memories' },
      { id: 'ap-ac-13', text: "What is an opinion you changed because of me?", bucket: 'learning' },
      { id: 'ap-ac-14', text: "What tiny luxury should be non-negotiable in life?", bucket: 'joy' },
      { id: 'ap-ac-15', text: "What little thing do I do that reminds you of your younger self?", bucket: 'likeness' },
      { id: 'ap-ac-16', text: "If we started a two-person book club, what’s book #1?", bucket: 'media' },
      { id: 'ap-ac-17', text: "When did you feel most supported by me recently?", bucket: 'support' },
      { id: 'ap-ac-18', text: "What’s a ridiculous family debate you still defend?", bucket: 'humor' },
      { id: 'ap-ac-19', text: "If we had a signature drink, what’s in it (mocktail allowed)?", bucket: 'fun' },
      { id: 'ap-ac-20', text: "What habit of yours should I steal immediately?", bucket: 'habits' },
      { id: 'ap-ac-21', text: "What gift did I give you that landed perfectly?", bucket: 'gifts' },
      { id: 'ap-ac-22', text: "What do you hope future-me brags about?", bucket: 'future' },
      { id: 'ap-ac-23', text: "Tell me a time you were hilariously wrong (bonus points if about me).", bucket: 'humor' },
      { id: 'ap-ac-24', text: "What’s a recipe I should learn exactly the way you make it?", bucket: 'food' },
      { id: 'ap-ac-25', text: "What smell instantly takes you back to our old place?", bucket: 'senses' },
      { id: 'ap-ac-26', text: "What movie did we over-quote the most?", bucket: 'media' },
      { id: 'ap-ac-27', text: "What’s a tiny boundary that improved our relationship?", bucket: 'boundaries' },
      { id: 'ap-ac-28', text: "What have you learned from watching me adult?", bucket: 'learning' },
      { id: 'ap-ac-29', text: "Complete the sentence: Our family is unstoppable when ___", bucket: 'identity' },
      { id: 'ap-ac-30', text: "What’s the nicest petty win you’ve had against me?", bucket: 'humor' }
    ],
    // P2 is Parent
    p2: [
      { id: 'ap-p-1', text: "What’s something I did as a parent that actually worked?", bucket: 'parenting' },
      { id: 'ap-p-2', text: "When did you realize you no longer needed my permission?", bucket: 'growth' },
      { id: 'ap-p-3', text: "Which of your talents came from me—be honest?", bucket: 'talent' },
      { id: 'ap-p-4', text: "What’s a family myth you now know was exaggerated (or true)?", bucket: 'stories' },
      { id: 'ap-p-5', text: "What do you think I’m secretly brilliant at?", bucket: 'praise' },
      { id: 'ap-p-6', text: "What was the moment you felt most proud of yourself recently?", bucket: 'pride' },
      { id: 'ap-p-7', text: "Teach me a life hack you learned that I never did.", bucket: 'advice' },
      { id: 'ap-p-8', text: "If we ran a tiny family business, what would we sell?", bucket: 'fun' },
      { id: 'ap-p-9', text: "What tradition do you want to pass to the next generation?", bucket: 'tradition' },
      { id: 'ap-p-10', text: "What’s a playlist we should build together?", bucket: 'music' },
      { id: 'ap-p-11', text: "What did I underestimate about you?", bucket: 'respect' },
      { id: 'ap-p-12', text: "What makes our conversations special now compared to before?", bucket: 'connection' },
      { id: 'ap-p-13', text: "What’s the funniest autocorrect fail in our family chat?", bucket: 'humor' },
      { id: 'ap-p-14', text: "If we could relive one ordinary day from the past, which one?", bucket: 'nostalgia' },
      { id: 'ap-p-15', text: "What did you teach me without realizing it?", bucket: 'learning' },
      { id: 'ap-p-16', text: "What’s a boundary I set that you appreciate now?", bucket: 'boundaries' },
      { id: 'ap-p-17', text: "What small kindness from me landed at the perfect time?", bucket: 'kindness' },
      { id: 'ap-p-18', text: "If you wrote a toast about our family, what’s the opener?", bucket: 'speech' },
      { id: 'ap-p-19', text: "What’s something about me that aged like fine wine?", bucket: 'humor' },
      { id: 'ap-p-20', text: "What everyday ritual keeps you grounded?", bucket: 'routine' },
      { id: 'ap-p-21', text: "What’s a tiny splurge you endorse 100%?", bucket: 'joy' },
      { id: 'ap-p-22', text: "What fear did you outgrow? How?", bucket: 'courage' },
      { id: 'ap-p-23', text: "What would our two-person podcast be called?", bucket: 'fun' },
      { id: 'ap-p-24', text: "What should I brag about you to my friends?", bucket: 'praise' },
      { id: 'ap-p-25', text: "What do you hope stays the same about us in 10 years?", bucket: 'future' },
      { id: 'ap-p-26', text: "What recipe from me do you secretly improve?", bucket: 'food' },
      { id: 'ap-p-27', text: "What’s a topic you can talk about for hours?", bucket: 'passion' },
      { id: 'ap-p-28', text: "What tradition should we retire gracefully?", bucket: 'tradition' },
      { id: 'ap-p-29', text: "What’s your most wholesome bad habit?", bucket: 'humor' },
      { id: 'ap-p-30', text: "Complete the sentence: We’re at our best when ___.", bucket: 'identity' }
    ]
  },

  'friend-friend': {
    // P1 Friend A
    p1: [
      { id: 'ff-a-1', text: "What’s our origin story—give me the cinematic version.", bucket: 'memories' },
      { id: 'ff-a-2', text: "What inside joke still makes you giggle in public?", bucket: 'humor' },
      { id: 'ff-a-3', text: "What friend superpower do I bring to the team?", bucket: 'praise' },
      { id: 'ff-a-4', text: "Pitch our two-person heist (no crimes—just snacks).", bucket: 'fun' },
      { id: 'ff-a-5', text: "What song is absolutely ‘us’ and why?", bucket: 'music' },
      { id: 'ff-a-6', text: "What’s a small way we make each other braver?", bucket: 'support' },
      { id: 'ff-a-7', text: "Tell the story of our most wholesome chaos.", bucket: 'memories' },
      { id: 'ff-a-8', text: "What do I bring to a road trip that upgrades the vibe?", bucket: 'travel' },
      { id: 'ff-a-9', text: "When did you know we’d be lifelong friends?", bucket: 'bond' },
      { id: 'ff-a-10', text: "What is our signature snack combo?", bucket: 'food' },
      { id: 'ff-a-11', text: "What compliment do I need to hear more often?", bucket: 'kindness' },
      { id: 'ff-a-12', text: "Which of my takes aged like fine wine?", bucket: 'humor' },
      { id: 'ff-a-13', text: "What trip should we plan that costs under $50?", bucket: 'fun' },
      { id: 'ff-a-14', text: "What skill of yours should I shamelessly steal?", bucket: 'learning' },
      { id: 'ff-a-15', text: "What ‘we’ tradition should we start this season?", bucket: 'tradition' },
      { id: 'ff-a-16', text: "Tell me about a time I had your back.", bucket: 'support' },
      { id: 'ff-a-17', text: "What store would we get banned from (for laughing)?", bucket: 'humor' },
      { id: 'ff-a-18', text: "What tiny thing I do makes your day better?", bucket: 'kindness' },
      { id: 'ff-a-19', text: "What’s a brag about you I should use more?", bucket: 'praise' },
      { id: 'ff-a-20', text: "What hobby should we try together for one week?", bucket: 'hobbies' },
      { id: 'ff-a-21', text: "What game do I absolutely underestimate you in?", bucket: 'games' },
      { id: 'ff-a-22', text: "Describe our friendship as a weather forecast.", bucket: 'fun' },
      { id: 'ff-a-23', text: "What podcast would we accidentally start?", bucket: 'fun' },
      { id: 'ff-a-24', text: "What phrase do I overuse—and love me for it anyway.", bucket: 'humor' },
      { id: 'ff-a-25', text: "What is the most ‘you’ gift I could give you under $10?", bucket: 'gifts' },
      { id: 'ff-a-26', text: "When do I inspire you the most?", bucket: 'inspiration' },
      { id: 'ff-a-27', text: "What is our official friendship holiday?", bucket: 'tradition' },
      { id: 'ff-a-28', text: "What’s a memory that lives rent-free in your brain (in a good way)?", bucket: 'memories' },
      { id: 'ff-a-29', text: "What chore would we be terrible at together?", bucket: 'humor' },
      { id: 'ff-a-30', text: "Write our friendship’s tagline in seven words.", bucket: 'identity' }
    ],
    // P2 Friend B
    p2: [
      { id: 'ff-b-1', text: "What’s your favorite ‘only we would think this is funny’ moment?", bucket: 'humor' },
      { id: 'ff-b-2', text: "What snack do I introduce that always wins the room?", bucket: 'food' },
      { id: 'ff-b-3', text: "What do you admire about how I handle stress?", bucket: 'praise' },
      { id: 'ff-b-4', text: "If we hosted a tiny festival, what’s its name?", bucket: 'fun' },
      { id: 'ff-b-5', text: "What city would we absolutely thrive in for a weekend?", bucket: 'travel' },
      { id: 'ff-b-6', text: "What’s the best advice you accidentally gave me?", bucket: 'advice' },
      { id: 'ff-b-7', text: "Tell me a mini-moment where you felt seen by me.", bucket: 'connection' },
      { id: 'ff-b-8', text: "What tradition should we bring back from our early days?", bucket: 'tradition' },
      { id: 'ff-b-9', text: "What’s our most elite meme reference?", bucket: 'humor' },
      { id: 'ff-b-10', text: "What role do I play in our duo that people miss?", bucket: 'identity' },
      { id: 'ff-b-11', text: "What would you put on our two-song EP?", bucket: 'music' },
      { id: 'ff-b-12', text: "What small ritual should future-us never skip?", bucket: 'routine' },
      { id: 'ff-b-13', text: "When did we win as a team recently?", bucket: 'wins' },
      { id: 'ff-b-14', text: "What weird hill did we both decide to die on?", bucket: 'humor' },
      { id: 'ff-b-15', text: "What’s a compliment you forget to give me?", bucket: 'kindness' },
      { id: 'ff-b-16', text: "If we ran a pop-up shop, what would we sell?", bucket: 'fun' },
      { id: 'ff-b-17', text: "What do I do that always breaks the ice?", bucket: 'praise' },
      { id: 'ff-b-18', text: "What is our minimalist travel kit?", bucket: 'travel' },
      { id: 'ff-b-19', text: "Tell a quick story where we were unintentionally hilarious.", bucket: 'memories' },
      { id: 'ff-b-20', text: "What’s a tiny challenge we should attempt this week?", bucket: 'hobbies' },
      { id: 'ff-b-21', text: "What’s our friendship superpower in one sentence?", bucket: 'identity' },
      { id: 'ff-b-22', text: "What movie do we quote too much but won’t stop?", bucket: 'media' },
      { id: 'ff-b-23', text: "What’s the last time I made you laugh-snort?", bucket: 'humor' },
      { id: 'ff-b-24', text: "What’s a memory we should re-create on purpose?", bucket: 'memories' },
      { id: 'ff-b-25', text: "What tiny thing about me deserves a standing ovation?", bucket: 'praise' },
      { id: 'ff-b-26', text: "What hobby should I never quit?", bucket: 'hobbies' },
      { id: 'ff-b-27', text: "What is the most ‘us’ photo we’ve taken?", bucket: 'memories' },
      { id: 'ff-b-28', text: "What’s a wholesome prank we should plan?", bucket: 'fun' },
      { id: 'ff-b-29', text: "What moment made our friendship feel unshakable?", bucket: 'bond' },
      { id: 'ff-b-30', text: "Write a supportive pep-talk line for me.", bucket: 'support' }
    ]
  },

  'kid-grandparent': {
    // P1 is Kid
    p1: [
      { id: 'kg-k-1', text: "What game did you love as a kid that I should learn?", bucket: 'childhood' },
      { id: 'kg-k-2', text: "Tell me about a funny rule your parents had.", bucket: 'family' },
      { id: 'kg-k-3', text: "What was your coolest snack or candy when you were my age?", bucket: 'food' },
      { id: 'kg-k-4', text: "What toy would past-you be jealous I have now?", bucket: 'fun' },
      { id: 'kg-k-5', text: "What was the silliest fashion when you were little?", bucket: 'humor' },
      { id: 'kg-k-6', text: "What is a song from your childhood I should hear?", bucket: 'music' },
      { id: 'kg-k-7', text: "What did you do after school for fun?", bucket: 'childhood' },
      { id: 'kg-k-8', text: "What smell reminds you of home growing up?", bucket: 'senses' },
      { id: 'kg-k-9', text: "What animal story from your life always makes people smile?", bucket: 'pets' },
      { id: 'kg-k-10', text: "What made you laugh so hard as a kid?", bucket: 'humor' },
      { id: 'kg-k-11', text: "What rule should we make up for our hangouts?", bucket: 'tradition' },
      { id: 'kg-k-12', text: "What is a tiny piece of advice I can try this week?", bucket: 'advice' },
      { id: 'kg-k-13', text: "What was your favorite rainy-day activity?", bucket: 'childhood' },
      { id: 'kg-k-14', text: "Tell me about a time you felt brave as a kid.", bucket: 'bravery' },
      { id: 'kg-k-15', text: "What dessert should we make together soon?", bucket: 'food' },
      { id: 'kg-k-16', text: "What is a toy or gadget you wish existed back then?", bucket: 'imagination' },
      { id: 'kg-k-17', text: "Teach me a secret handshake or greeting!", bucket: 'fun' },
      { id: 'kg-k-18', text: "What was your best school lunch trade?", bucket: 'school' },
      { id: 'kg-k-19', text: "What animal would you have as a magical pet?", bucket: 'imagination' },
      { id: 'kg-k-20', text: "What nice thing can I do that would make you smile big?", bucket: 'kindness' },
      { id: 'kg-k-21', text: "What place near home felt like adventure land?", bucket: 'memories' },
      { id: 'kg-k-22', text: "What was your funniest sports moment?", bucket: 'humor' },
      { id: 'kg-k-23', text: "What is a family story I should memorize?", bucket: 'legacy' },
      { id: 'kg-k-24', text: "What should be our official snack when we hang out?", bucket: 'food' },
      { id: 'kg-k-25', text: "What cartoon did everyone watch then?", bucket: 'media' },
      { id: 'kg-k-26', text: "What is a pocket-sized skill you can teach me?", bucket: 'skills' },
      { id: 'kg-k-27', text: "What made your best friend special back then?", bucket: 'friendship' },
      { id: 'kg-k-28', text: "What is a nice habit I can practice daily?", bucket: 'habits' },
      { id: 'kg-k-29', text: "What do you think I’ll be amazing at when I’m older?", bucket: 'future' },
      { id: 'kg-k-30', text: "Tell me the story of a tiny victory that meant a lot.", bucket: 'wins' }
    ],
    // P2 is Grandparent
    p2: [
      { id: 'kg-g-1', text: "What is something you do that makes me giggle every time?", bucket: 'humor' },
      { id: 'kg-g-2', text: "What new thing did you learn recently that surprised you?", bucket: 'learning' },
      { id: 'kg-g-3', text: "What game should we invent together?", bucket: 'fun' },
      { id: 'kg-g-4', text: "What kindness did you show someone this week?", bucket: 'kindness' },
      { id: 'kg-g-5', text: "What is your current top snack—and why is it unbeatable?", bucket: 'food' },
      { id: 'kg-g-6', text: "What makes a perfect grandparent-kid day?", bucket: 'routine' },
      { id: 'kg-g-7', text: "What talent of yours do I need to brag about to my friends?", bucket: 'praise' },
      { id: 'kg-g-8', text: "What silly face should be our official selfie?", bucket: 'humor' },
      { id: 'kg-g-9', text: "What is your favorite way to help at home?", bucket: 'home' },
      { id: 'kg-g-10', text: "What makes you feel big and brave lately?", bucket: 'bravery' },
      { id: 'kg-g-11', text: "What tradition should we start for our calls/visits?", bucket: 'tradition' },
      { id: 'kg-g-12', text: "What song should we sing loudly together soon?", bucket: 'music' },
      { id: 'kg-g-13', text: "What’s a joke I should learn so I can tell it to you later?", bucket: 'humor' },
      { id: 'kg-g-14', text: "What was the best part of your week—and why?", bucket: 'wins' },
      { id: 'kg-g-15', text: "What nice thing did someone do for you that you want to pass on?", bucket: 'kindness' },
      { id: 'kg-g-16', text: "If we built a secret fort, what would the rules be?", bucket: 'fun' },
      { id: 'kg-g-17', text: "What superpower would you choose for one day?", bucket: 'imagination' },
      { id: 'kg-g-18', text: "What makes our time together special to you?", bucket: 'connection' },
      { id: 'kg-g-19', text: "What silly award should I give you right now?", bucket: 'humor' },
      { id: 'kg-g-20', text: "What makes you feel most loved at home?", bucket: 'home' },
      { id: 'kg-g-21', text: "What should we cook or bake next visit?", bucket: 'food' },
      { id: 'kg-g-22', text: "What is your best dance move called?", bucket: 'fun' },
      { id: 'kg-g-23', text: "When do you feel like a great friend?", bucket: 'friendship' },
      { id: 'kg-g-24', text: "What do you want to teach me next time?", bucket: 'skills' },
      { id: 'kg-g-25', text: "If we had a mascot, what would it be?", bucket: 'fun' },
      { id: 'kg-g-26', text: "What makes school most fun right now?", bucket: 'school' },
      { id: 'kg-g-27', text: "What is a small goal you’re excited about?", bucket: 'future' },
      { id: 'kg-g-28', text: "What is your favorite thing about our family?", bucket: 'identity' },
      { id: 'kg-g-29', text: "What helps when you feel wobbly?", bucket: 'advice' },
      { id: 'kg-g-30', text: "What silly tradition should we invent for birthdays?", bucket: 'tradition' }
    ]
  }
}

export function getRandomQuestionFor(rel: Relationship, side: RelationSide): RelationQuestion {
  const pool = questions[rel][side]
  const idx = Math.floor(Math.random() * pool.length)
  return pool[idx]
}
