// src/lib/questions-newpairs.ts
type Q = { id: string; text: string; bucket: string };

export const extraQuestions = {
  'kid-kid': {
    p1: kidKidP1(),
    p2: kidKidP2(),
  },
  'sibling-sibling': {
    p1: sibSibP1(),
    p2: sibSibP2(),
  },
} as const;

function kidKidP1(): Q[] {
  return [
    { id: 'k2k-p1-001', text: "What’s your ultimate recess game and why is it unbeatable?", bucket: 'fun' },
    { id: 'k2k-p1-002', text: "If we had a secret handshake, what silly move must it include?", bucket: 'fun' },
    { id: 'k2k-p1-003', text: "What snack would you trade anything for at lunch?", bucket: 'food' },
    { id: 'k2k-p1-004', text: "If our backpacks could talk, what would yours complain about?", bucket: 'imagination' },
    { id: 'k2k-p1-005', text: "What tiny superpower would make school 10% better?", bucket: 'imagination' },
    { id: 'k2k-p1-006', text: "Which teacher would win a dance-off and what’s their move?", bucket: 'school' },
    { id: 'k2k-p1-007', text: "What’s your best trick for making homework less boring?", bucket: 'school' },
    { id: 'k2k-p1-008', text: "If we built a fort, what’s the rule that gets you kicked out?", bucket: 'fun' },
    { id: 'k2k-p1-009', text: "Describe your dream field trip with three stops.", bucket: 'adventure' },
    { id: 'k2k-p1-010', text: "What’s the funniest thing you’ve heard on the playground?", bucket: 'fun' },
    { id: 'k2k-p1-011', text: "If you were principal for a day, what’s your first announcement?", bucket: 'school' },
    { id: 'k2k-p1-012', text: "What’s a small kindness you noticed this week?", bucket: 'kindness' },
    { id: 'k2k-p1-013', text: "What silly holiday should we invent and how do we celebrate?", bucket: 'imagination' },
    { id: 'k2k-p1-014', text: "What’s your best joke that always lands?", bucket: 'fun' },
    { id: 'k2k-p1-015', text: "Which animal would be a hilarious gym teacher and why?", bucket: 'imagination' },
    { id: 'k2k-p1-016', text: "What’s your favorite way to help a friend feel better?", bucket: 'kindness' },
    { id: 'k2k-p1-017', text: "If we made a club, what would it be called and who can join?", bucket: 'friends' },
    { id: 'k2k-p1-018', text: "What’s the most epic Lego build you can imagine?", bucket: 'build' },
    { id: 'k2k-p1-019', text: "Which song makes you dance even if you don’t want to?", bucket: 'music' },
    { id: 'k2k-p1-020', text: "If homework was edible, what flavor should it be?", bucket: 'food' },
    { id: 'k2k-p1-021', text: "What little win did you have today?", bucket: 'wins' },
    { id: 'k2k-p1-022', text: "What’s a rule you wish adults understood about kids?", bucket: 'life' },
    { id: 'k2k-p1-023', text: "What’s a game we invented that should be famous?", bucket: 'fun' },
    { id: 'k2k-p1-024', text: "If your shoes could leave drawings, what trail would you make?", bucket: 'imagination' },
    { id: 'k2k-p1-025', text: "What’s your kindest brag about yourself?", bucket: 'kindness' },
    { id: 'k2k-p1-026', text: "Which class would you teach for 20 minutes?", bucket: 'school' },
    { id: 'k2k-p1-027', text: "What’s the best playground invention you’ve seen?", bucket: 'fun' },
    { id: 'k2k-p1-028', text: "What’s your favorite rainy-day activity?", bucket: 'home' },
    { id: 'k2k-p1-029', text: "If we had a two-person costume, what would we be?", bucket: 'fun' },
    { id: 'k2k-p1-030', text: "What’s something you’re getting quietly better at?", bucket: 'growth' },
  ];
}
function kidKidP2(): Q[] {
  return [
    { id: 'k2k-p2-001', text: "What’s your favorite recess story starring you?", bucket: 'fun' },
    { id: 'k2k-p2-002', text: "If you could rename our class, what’s the new name?", bucket: 'school' },
    { id: 'k2k-p2-003', text: "Which snack do you guard like a dragon?", bucket: 'food' },
    { id: 'k2k-p2-004', text: "If your pencil wrote only compliments, what would it write first?", bucket: 'kindness' },
    { id: 'k2k-p2-005', text: "What tiny gadget would make mornings easier?", bucket: 'life' },
    { id: 'k2k-p2-006', text: "Who’s the most unexpectedly funny person at school?", bucket: 'school' },
    { id: 'k2k-p2-007', text: "What’s your go-to way to include someone new?", bucket: 'kindness' },
    { id: 'k2k-p2-008', text: "If we had secret nicknames, what would yours be?", bucket: 'friends' },
    { id: 'k2k-p2-009', text: "What field trip souvenir would you treasure forever?", bucket: 'adventure' },
    { id: 'k2k-p2-010', text: "Which classroom object deserves a trophy and why?", bucket: 'school' },
    { id: 'k2k-p2-011', text: "If you designed a playground, what’s the wildcard feature?", bucket: 'build' },
    { id: 'k2k-p2-012', text: "What compliment do you like hearing the most?", bucket: 'kindness' },
    { id: 'k2k-p2-013', text: "What’s a silly rule you’d add to gym class?", bucket: 'fun' },
    { id: 'k2k-p2-014', text: "What small thing makes you feel super brave?", bucket: 'growth' },
    { id: 'k2k-p2-015', text: "Which animal would make the best librarian and why?", bucket: 'imagination' },
    { id: 'k2k-p2-016', text: "What’s a creative way to make chores more fun?", bucket: 'home' },
    { id: 'k2k-p2-017', text: "What’s a new rule for our imaginary club?", bucket: 'friends' },
    { id: 'k2k-p2-018', text: "What’s your most joyful five minutes this week?", bucket: 'wins' },
    { id: 'k2k-p2-019', text: "If you could pause time for 60 seconds, what would you do?", bucket: 'imagination' },
    { id: 'k2k-p2-020', text: "Which song should automatically play at lunchtime?", bucket: 'music' },
    { id: 'k2k-p2-021', text: "What’s a promise you keep to yourself?", bucket: 'growth' },
    { id: 'k2k-p2-022', text: "Who’s your kindness role model and why?", bucket: 'kindness' },
    { id: 'k2k-p2-023', text: "What sport do you secretly want to invent?", bucket: 'fun' },
    { id: 'k2k-p2-024', text: "What’s your perfect rainy-day snack combo?", bucket: 'food' },
    { id: 'k2k-p2-025', text: "If your shoes squeaked a word, what would they say?", bucket: 'imagination' },
    { id: 'k2k-p2-026', text: "What’s a hobby you’d teach me in 5 minutes?", bucket: 'friends' },
    { id: 'k2k-p2-027', text: "What’s the most underrated school subject and why?", bucket: 'school' },
    { id: 'k2k-p2-028', text: "What’s a kind thing you did and didn’t tell anyone?", bucket: 'kindness' },
    { id: 'k2k-p2-029', text: "If we wrote a two-person comic, what’s chapter one?", bucket: 'imagination' },
    { id: 'k2k-p2-030', text: "What are you excited to learn next?", bucket: 'growth' },
  ];
}

function sibSibP1(): Q[] {
  return [
    { id: 'sib-p1-001', text: "What’s a tiny family tradition you secretly love?", bucket: 'family' },
    { id: 'sib-p1-002', text: "What old argument do we both laugh about now?", bucket: 'memories' },
    { id: 'sib-p1-003', text: "Which of our inside jokes deserves a trophy?", bucket: 'fun' },
    { id: 'sib-p1-004', text: "What’s a compliment you wish you’d said to me sooner?", bucket: 'kindness' },
    { id: 'sib-p1-005', text: "If we ran a food truck, what’s our signature dish?", bucket: 'food' },
    { id: 'sib-p1-006', text: "Which shared chore forged us in fire?", bucket: 'home' },
    { id: 'sib-p1-007', text: "What place from childhood would you teleport us to for an hour?", bucket: 'memories' },
    { id: 'sib-p1-008', text: "What’s a way we’re similar that makes you smile?", bucket: 'family' },
    { id: 'sib-p1-009', text: "Which family recipe deserves to be passed down forever?", bucket: 'food' },
    { id: 'sib-p1-010', text: "What playlist is pure sibling chaos—in a good way?", bucket: 'music' },
    { id: 'sib-p1-011', text: "What’s a small kindness you noticed me doing?", bucket: 'kindness' },
    { id: 'sib-p1-012', text: "Which house rule aged like fine wine—and which didn’t?", bucket: 'home' },
    { id: 'sib-p1-013', text: "What silly nickname did we retire—and should it come back?", bucket: 'fun' },
    { id: 'sib-p1-014', text: "What’s a life skill you learned first and rescued me with?", bucket: 'growth' },
    { id: 'sib-p1-015', text: "If we wrote a sibling handbook, what’s rule #1?", bucket: 'family' },
    { id: 'sib-p1-016', text: "What’s a gift you gave me that really landed?", bucket: 'kindness' },
    { id: 'sib-p1-017', text: "What’s the funniest thing we got in trouble for?", bucket: 'memories' },
    { id: 'sib-p1-018', text: "Which holiday were we absolute pros at optimizing?", bucket: 'memories' },
    { id: 'sib-p1-019', text: "What do you admire about how I handle stress?", bucket: 'growth' },
    { id: 'sib-p1-020', text: "If we started a micro-tradition this year, what would it be?", bucket: 'family' },
    { id: 'sib-p1-021', text: "What’s a ‘sibling superpower’ you think we have?", bucket: 'family' },
    { id: 'sib-p1-022', text: "Which family photo deserves a dramatic reenactment?", bucket: 'fun' },
    { id: 'sib-p1-023', text: "What’s a way we’ve grown more supportive over time?", bucket: 'growth' },
    { id: 'sib-p1-024', text: "What do you want our future ‘us’ to remember to do?", bucket: 'future' },
    { id: 'sib-p1-025', text: "What’s a meal that tastes like home for you?", bucket: 'food' },
    { id: 'sib-p1-026', text: "What’s a skill you’d like to swap with me for a week?", bucket: 'growth' },
    { id: 'sib-p1-027', text: "If we hosted a game night, what’s our unbeatable format?", bucket: 'fun' },
    { id: 'sib-p1-028', text: "What tiny habit has improved your days recently?", bucket: 'life' },
    { id: 'sib-p1-029', text: "What’s a compliment for our parents you haven’t said out loud?", bucket: 'family' },
    { id: 'sib-p1-030', text: "What’s your favorite version of me you’ve seen recently?", bucket: 'kindness' },
  ];
}
function sibSibP2(): Q[] {
  return [
    { id: 'sib-p2-001', text: "What’s a sibling memory that deserves a movie scene?", bucket: 'memories' },
    { id: 'sib-p2-002', text: "What’s something I do that feels very ‘us’?", bucket: 'family' },
    { id: 'sib-p2-003', text: "Which tradition should we steal from another family?", bucket: 'future' },
    { id: 'sib-p2-004', text: "What’s a tiny apology you want to offer from long ago?", bucket: 'kindness' },
    { id: 'sib-p2-005', text: "If we swapped jobs for a day, what would be hilarious?", bucket: 'fun' },
    { id: 'sib-p2-006', text: "What snack instantly teleports you to our childhood kitchen?", bucket: 'food' },
    { id: 'sib-p2-007', text: "Which road trip with me had the best vibe?", bucket: 'memories' },
    { id: 'sib-p2-008', text: "What’s a new sibling ritual we could start monthly?", bucket: 'future' },
    { id: 'sib-p2-009', text: "What’s a way you’ve felt cheered on by me?", bucket: 'kindness' },
    { id: 'sib-p2-010', text: "What skill of mine do you want the tutorial for?", bucket: 'growth' },
    { id: 'sib-p2-011', text: "Which inside joke will we still think is funny at 90?", bucket: 'fun' },
    { id: 'sib-p2-012', text: "What’s something you’re proud of me for lately?", bucket: 'kindness' },
    { id: 'sib-p2-013', text: "Which family myth still cracks you up?", bucket: 'memories' },
    { id: 'sib-p2-014', text: "What home smell is pure nostalgia for you?", bucket: 'memories' },
    { id: 'sib-p2-015', text: "What would our sibling crest have on it?", bucket: 'imagination' },
    { id: 'sib-p2-016', text: "What’s a way we balance each other well?", bucket: 'family' },
    { id: 'sib-p2-017', text: "What’s a small way I can support you this month?", bucket: 'kindness' },
    { id: 'sib-p2-018', text: "What board game should be illegal in our house and why?", bucket: 'fun' },
    { id: 'sib-p2-019', text: "What recipe do you want me to master so we can share it?", bucket: 'food' },
    { id: 'sib-p2-020', text: "If we wrote a toast for each other, what line is essential?", bucket: 'kindness' },
    { id: 'sib-p2-021', text: "What’s a tiny luxury we both deserve more often?", bucket: 'life' },
    { id: 'sib-p2-022', text: "What holiday role should we assign each other?", bucket: 'family' },
    { id: 'sib-p2-023', text: "What advice from me actually helped?", bucket: 'growth' },
    { id: 'sib-p2-024', text: "What do you think our superpower duo name would be?", bucket: 'imagination' },
    { id: 'sib-p2-025', text: "What’s a place we should re-visit together and why?", bucket: 'memories' },
    { id: 'sib-p2-026', text: "Which chore race did you absolutely destroy me at?", bucket: 'home' },
    { id: 'sib-p2-027', text: "What’s a low-effort, high-joy plan we can repeat?", bucket: 'future' },
    { id: 'sib-p2-028', text: "What compliment about you would you like me to remember?", bucket: 'kindness' },
    { id: 'sib-p2-029', text: "If we had a sibling podcast, what’s episode one?", bucket: 'fun' },
    { id: 'sib-p2-030', text: "What are you excited for us to laugh about years from now?", bucket: 'future' },
  ];
}
